### ISSUE TITLE
Retrieving Relationships from Direct Relationships

### ISSUE THREAD

**Issue by matcartmill** [sander3/laravel-gdpr#13]
Given that a User has a relationship with `Restaurant`, and `Restaurant` has many `MenuItems`, how are we able to retrieve the `MenuItems` for that `Restaurant`?

I have tried making `Restaurant` `Portable` and defining with `$gdprWith` for that model, but that does not work.

As well, it appears as though all properties on a model with a relationship (`Restaurant` in this case) will be visible, regardless of making the `Restaurant` model `Portable` and assigning `$gdprVisible` property to exclude things like `id`, `hash`, etc. Will be opening a separate bug for this.

**Comment by sander3** [comment]
Hi there,

In order to retrieve a relationship's relation, you should use the dot notation:

```php
$gdprWith = ['restaurant.menuItems'];
```
