### ISSUE TITLE
How to use this with Socialite?

### ISSUE THREAD

**Issue by matcartmill** [sander3/laravel-gdpr#15]
If a user has to enter a password to download their data, how do plan (if not already) to handle the case where a user signed up via Facebook or other OAuth service? In most of these cases, a password will not be set for the user, or a randomly generated password will be set at the time of account creation.

**Comment by earthroot** [comment]
Hey, would it be too much to ask how exactly I'd override the attemptLogin() method? It's unclear to me, unless I want to move all the package logic into the app, which I don't.
Thanks!

**Comment by sander3** [comment]
Hi there!

One way to do it is to create your own `GdprController` (in your app namespace) and extend the original controller. Don't forget to register your new route. I will try to provide some examples next week.

I will also refactor the `GdprController` in the future to make it easier to roll out your own authentication logic.

**Comment by sander3** [comment]
Quick update: you're now able to disable re-authentication. See 6e2bf4d1a5995508fd35679f837bedd2a175cd02.

I will tag a new release later today.

**Comment by sander3** [comment]
https://github.com/sander3/laravel-gdpr/releases/tag/v1.5.0

**Comment by earthroot** [comment]
Thanks for the update, I ended up keeping the extended controller as you suggested, as I want to cases: 1) user has a normal account, which I'd like to reauthenticate, 2) user comes through socialiate where I'd implement a custom login, thus i'd not use  https://github.com/sander3/laravel-gdpr/commit/6e2bf4d1a5995508fd35679f837bedd2a175cd02

**Comment by sander3** [comment]
Thanks for your update. Would you like to share your implementation?I will use it to determine future use cases.


Aug 5, 2018, 5:12 PM by notifications@github.com:
