### ISSUE TITLE
How to encrypt existing data?

### ISSUE THREAD

**Issue by ameerElsherif** [sander3/laravel-gdpr#23]
Data encryption works just fine on newer inserted data.
But how can I apply the encryption on already existing data?

Also, what data type should I use for encrypted columns?

**Comment by sander3** [comment]
Hi there,

I would create a migration to encrypt existing data. My strategy would be:

1. Get all Eloquent models you want to encrypt.
2. Iterate over all models.
    1. Iterate over your model's `$encrypted` array.
    2. Replace all values using `encrypt($value)`.
    3. Save.

You should use the `TEXT` data type.

**Comment by ameerElsherif** [comment]
Thanks!

For any one who needs this in the future you will need to use the following syntax while replacing model values:
`$this->attributes[$field] = encrypt($this->getOriginal($field));`
This is necessary to skip the encryption mutator or else values will be encrypted twice.
