### ISSUE TITLE
How to hide relation attributes?

### ISSUE THREAD

**Issue by robertogallea** [sander3/laravel-gdpr#26]
Hi, I am not able to hide specific attributes from relations. I have tried the following:

1. in `User` set `$gdprHidden = ['relation.attribute']` 

2. Add `Portable` trait to `Relation` and inside it set `$gdprHidden = ['attribute']` 

What am I missing? Thank you.

**Comment by sander3** [comment]
Hi there,

Number one will not work. Number two does work, but you forgot to implement the `PortableContract ` on the relation.

**Comment by robertogallea** [comment]
Thank you for your reply. However I still have some problems.

I tried also what you told, but I thought it was uncorrect, since I got an exception.

I have the following (simplifying):
```php
class User extends Authenticable implements PortableContract
{
    use Portable;

    protected $gdprWith = ['relation'];

    protected $gdprHidden = ['password', 'remember_token', 'created_at', 'updated_at'];   

    public function relation()
    {
        return $this->hasOne(Relation::class);
    }

    public function getNameAttribute()
    {
        return ucfirst(strtolower($this->person->name)); // <-- HERE LIES THE PROBLEM
    }

   ...
}
```
and
```php
class Relation extends Model implements PortableContract
{
    use Portable;

    protected $gdprHidden = ['id'];
    
    ...
}
```

with this setup I get the following exception:

`Property [name] does not exist on this collection instance.`

where `name` is an (existing) attribute of `Relation` used by an accessor in `User`

It seems that, notwithstanding it is a `hasOne` relation, your package loads it as a `Collection` instead of a single object, so the accessor fails. 

If a remove `Relation` from `$gdprWith` the relation is correctly loaded but no filtering is performed on the attributes. Any ideas why relations are always load as a `Collection`?

**Comment by sander3** [comment]
It seems like the `Portable` trait lacks `hasOne` and `belongsTo` support. Unfortunately, I don't have time to fix this properly this week.

Feel free to use the following workaround for the time being. I'll get back to you with a new release.

```php
    /**
     * Load and transform a portable relation.
     *
     * @param  string  $relation
     * @return void
     */
    private function loadPortableRelation(string $relation)
    {
        $items = $this
            ->$relation()
            ->get()
            ->transform(function ($item) {
                return $item->portable();
            });

        if ($items->count() === 1) {
            $items = $items->first();
        }

        $this->attributes[$relation] = $items;
    }
```

**Comment by robertogallea** [comment]
Ok, thank you for your time

**Comment by robertogallea** [comment]
Thanks!
