### ISSUE TITLE
Update to Laravel 8

### ISSUE THREAD

**Issue by bumbummen99** [sander3/laravel-gdpr#32]
Are there any plans to update this to Laravel 8?

**Comment by sander3** [comment]
Yes, there are. It will probably be released somewhere next week.

I'm going through the changes between Laravel 7 and 8 to see if I even need to change anything. If not, it'll be released soon.

**Comment by sander3** [comment]
It seemed there were no breaking changes whatsoever. Please check out v1.5.5 for Laravel 8 'support'.

I might clean up the routing later on, but this is completely optional since the service provider passed the namespace.
