### ISSUE TITLE
Laravel 8 incompatibility issue

### ISSUE THREAD

**Issue by maicol07** [sander3/laravel-gdpr#34]
Laravel 8 introduced the possibility to have a Models folder inside the app directory.

Currently, the package imports App\\User but if the User.php file is in the Models directory the correct namespace is App\\Models\\User. This raises an exception.

https://github.com/sander3/laravel-gdpr/blob/b5560965348eb2a7cdba83947ac2ce8ceb9a00c7/src/Console/Commands/Cleanup.php#L5

**Comment by sander3** [comment]
https://github.com/sander3/laravel-gdpr/pull/36
