### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by joniand** [sander3/laravel-gdpr#43]
Are there any plans to update this to Laravel 9?

**Comment by sander3** [comment]
Hi there,

Yes, I'm planning on upgrading all my packages to support Laravel 9 this weekend. Feel free to create PR tho.

**Comment by sander3** [comment]
@joniand Could you try https://github.com/sander3/laravel-gdpr/pull/44?

**Comment by joniand** [comment]
@sander3 Yep, seems to work perfectly! Thanks!
