### ISSUE TITLE
show only some relationship attributes

### ISSUE THREAD

**Issue by dgillier** [sander3/laravel-gdpr#46]
Hello,

Thanks for this great package !

I tried to hide some of the relationship attributes by using your $gdprVisible property with just the fields I want  visible, working ok for the User model but not for the relationships.
(I  tried to add some of the relationship  attributes like 'bookings.name'  in $gdprVisible, but it's not working)

Anyway to do that ?
Thanks, Denis

**Comment by andy-laravel** [comment]
I came here to ask the same question

**Comment by prattcmp** [comment]
The only way I found to do this is not to use the `$gdprXYZ` attributes at all and just use `toPortableArray()`.

**Comment by sander3** [comment]
You should be able to do so by adding a `$gdprVisible` array to the related model.
